version: "3.9"
services:
  liferay-portal:
    image: liferay/portal:7.4.3.112-ga112
    ports:
      - "8080:8080"
    links:
      - db-postgres
    volumes:
      - ./lr-mount:/mnt/liferay
  db-postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=liferay
      - POSTGRES_PASSWORD=master
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: